### ISSUE TITLE
App adds a bunch of HTML tags if line breaks are inserted when clicking on "Share with .." buttons

### ISSUE THREAD

**Issue by jonathan-wiens** [berlin-international-community-church/prayer-praise-app#22]
When I add a prayer or praise request, enter text and then click on "Share with prayer team" or "Share with everyone" the app adds to my input a bunch of HTML tags, like this:

Test&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;test&lt;/div&gt;

This only happens if I have line breaks in the input.

**Comment by rocky-jaiswal** [comment]
This should be fixed now on - https://prayersnpraises.online/ along with few other fixes.

**Comment by jonathan-wiens** [comment]
Confirmed. Looks great!
